# Generated by Django 2.2 on 2021-07-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='favorite_color',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='sample',
            name='favorite_food',
            field=models.CharField(max_length=5),
        ),
    ]
